### ISSUE TITLE
Incompatible with Fabric-API

### ISSUE THREAD

**Issue by TwoPointInfinity** [andrewlalis/SpeedCarts#5]
mod version 1.3.0
Java version: 
Milestone 1 build of IBM Semeru Runtime Open Edition for Java 17 with Eclipse OpenJ9 jdk-17.0.1+12_openj9-0.29.1-m1
https://github.com/ibmruntimes/semeru17-binaries/releases/tag/jdk-17.0.1%2B12_openj9-0.29.1-m1

```
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:68)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.RuntimeException: Error creating Mixin config modid.mixins.json for mod speed-carts
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	... 5 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config modid.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 8 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 11 more

```

**Comment by TwoPointInfinity** [comment]
Other installed mods are:
disfabric-1.18-1.3.5.jar
EditSign-1.18-2.2.5.jar
fabric-api-0.44.0+1.18.jar
LuckPerms-Fabric-5.3.86.jar
speed-carts-1.3.0.jar
anti-xray-mc1.18-1.1.1.jar
"C:\Users\twopo\Desktop\Server\mods\blockmeter-1.6-fabric_1_18.jar"

**Comment by andrewlalis** [comment]
Can you upload the entire stacktrace/crash report? Because I haven't encountered this when building the new version, and I don't know how to reproduce your issue.

**Comment by TwoPointInfinity** [comment]
here'e my full launch log, if i remove speed carts the game launches fine.  Please let em know if you need more information or if maybe i did something wrong here. 
https://pastebin.com/FjjVZLxk

**Comment by andrewlalis** [comment]
> [12:26:54] [main/INFO]: Compatibility level set to JAVA_16
I see this in the log, which means that something in your configuration is setting your Fabric server to try to be compatible with Jav 16, but Minecraft 1.18 uses Java 17, which is also what Speed Carts is built with. Now, I'm not really familiar with fabric myself, since I just made this mod as a one-off thing, so I don't know exactly where you'd look to fix or set the compatibility mode for your server, or it might be a compatibility issue where other mods are requiring support for an older version of java (although that in itself should cause issues since only Java 17 should work).

**Comment by TwoPointInfinity** [comment]
I dont even have java 16.

**Comment by TwoPointInfinity** [comment]
The fabric API is what sets the "Compatibility level set to JAVA_16"
with only the fabric API it does this

**Comment by TwoPointInfinity** [comment]
#7
